In [1]:
#Import libraries
import pandas as pd

In [2]:
#Load Data in Dataframe
import time
start_time = time.time()
train_data = pd.read_csv('train_data.csv')
print("--- %s seconds ---" % (time.time() - start_time))
train_data

--- 295.47053122520447 seconds ---

,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,B_3,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
0,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-03-09,0.938469,0.001733,0.008724,1.006838,0.009228,0.124035,0.008771,0.004709,...,NaN,NaN,NaN,0.002427,0.003706,0.003818,NaN,0.000569,0.000610,0.002674
1,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-04-07,0.936665,0.005775,0.004923,1.000653,0.006151,0.126750,0.000798,0.002714,...,NaN,NaN,NaN,0.003954,0.003167,0.005032,NaN,0.009576,0.005492,0.009217
2,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-05-28,0.954180,0.091505,0.021655,1.009672,0.006815,0.123977,0.007598,0.009423,...,NaN,NaN,NaN,0.003269,0.007329,0.000427,NaN,0.003429,0.006986,0.002603
3,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-06-13,0.960384,0.002455,0.013683,1.002700,0.001373,0.117169,0.000685,0.005531,...,NaN,NaN,NaN,0.006117,0.004516,0.003200,NaN,0.008419,0.006527,0.009600
4,0000099d6bd597052cdcda90ffabf56573fe9d7c79be5f...,2017-07-16,0.947248,0.002483,0.015193,1.000727,0.007605,0.117325,0.004653,0.009312,...,NaN,NaN,NaN,0.003671,0.004946,0.008889,NaN,0.001670,0.008126,0.009827
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5531446,fffff1d38b785cef84adeace64f8f83db3a0c31e8d92ea...,2017-11-05,0.979332,0.416013,0.020818,0.828199,0.003487,0.090743,0.005340,0.025139,...,NaN,NaN,NaN,0.006838,0.003680,0.000457,NaN,0.000905,0.001498,0.002774
5531447,fffff1d38b785cef84adeace64f8f83db3a0c31e8d92ea...,2017-12-23,0.984907,0.296536,0.007209,0.812610,0.005904,0.079886,0.002243,0.023691,...,NaN,NaN,NaN,0.003310,0.007097,0.007857,NaN,0.002777,0.008225,0.008856
5531448,fffff1d38b785cef84adeace64f8f83db3a0c31e8d92ea...,2018-01-06,0.983019,0.443984,0.013151,0.815422,0.003457,0.100503,0.002111,0.012343,...,NaN,NaN,NaN,0.009955,0.009994,0.001088,NaN,0.005693,0.006773,0.005566
5531449,fffff1d38b785cef84adeace64f8f83db3a0c31e8d92ea...,2018-02-06,0.969861,0.442553,0.009855,1.003541,0.005117,0.101802,0.009930,0.008578,...,NaN,NaN,NaN,0.005541,0.006564,0.009883,NaN,0.008123,0.001168,0.003983
5531450,fffff1d38b785cef84adeace64f8f83db3a0c31e8d92ea...,2018-03-14,0.982175,0.002474,0.000077,0.992880,0.000809,0.119165,0.003287,0.014092,...,NaN,NaN,NaN,0.007316,0.002888,0.006207,NaN,0.005110,0.003184,0.001914

In [4]:
#df Shape
train_data.shape

(5531451, 190)

In [5]:
from sklearn.model_selection import train_test_split

In [7]:
#Split data in to train and test data sets
Train25, Test75 = train_test_split(train_data, \
                                           test_size = 0.75,\
                                           random_state = 10) 

#Total Count
Train25.shape

(1382862, 190)

In [9]:
Train25.to_csv('Train25.csv')

In [10]:
#Load Data in Dataframe
import time
start_time = time.time()
train_data = pd.read_csv('Train25.csv')
print("--- %s seconds ---" % (time.time() - start_time))
train_data

--- 91.33146905899048 seconds ---

,Unnamed: 0,customer_ID,S_2,P_2,D_39,B_1,B_2,R_1,S_3,D_41,...,D_136,D_137,D_138,D_139,D_140,D_141,D_142,D_143,D_144,D_145
0,4580744,d3cbc7762fa018a0c0cccd8a89fb9d54a26f9097569389...,2018-03-17,0.927437,0.007716,0.002012,0.811036,0.001816,0.145747,0.005826,...,NaN,NaN,NaN,0.003616,0.006932,0.008604,NaN,0.003723,0.008369,0.007014
1,1129269,3423938309c0311e273f994fb75c17c051248bec00b142...,2018-02-27,0.692903,0.007248,0.008110,0.813047,0.001296,0.182255,0.008221,...,NaN,NaN,NaN,0.005810,0.007510,0.001479,NaN,0.008584,0.003927,0.000265
2,786878,24830d3e3a6739380c1e4f410cdbc1cccd8670ca4efac5...,2017-10-25,0.760664,0.007164,0.003502,0.816307,0.008692,NaN,0.004170,...,NaN,NaN,NaN,0.004483,0.000421,0.003531,NaN,0.005391,0.001890,0.008278
3,417099,136e58c0698fa15569bbb189ed3f67d4d0773eb1f40475...,2017-07-14,0.541180,0.006883,0.592058,0.043188,0.005739,0.140962,0.009141,...,NaN,NaN,NaN,0.001435,0.003579,0.004951,NaN,0.007757,0.002797,0.000894
4,2559303,7613e081c2fa384bfb6b1df0bab37a0ef29a27cccf5e83...,2017-11-17,0.368668,0.031484,0.453274,0.027807,0.002330,0.263603,0.002230,...,NaN,NaN,NaN,0.006034,0.007786,0.009002,NaN,0.008526,0.003591,0.007756
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1382857,1976281,5b3ced2cebbe1d518a3a6645fe165577cdaa210e61579a...,2017-05-27,0.606872,0.391428,0.039005,1.008506,0.008201,0.038661,0.007313,...,0.25668,0.004762,0.005549,0.005664,0.007183,0.009182,NaN,0.001837,0.007191,0.001326
1382858,3251323,96380ff3221345f0c80f61597c355958598646b3e024f7...,2017-07-22,0.875765,0.001855,0.030664,1.002463,0.001630,0.104359,0.003367,...,NaN,NaN,NaN,0.009151,0.009526,0.007361,NaN,0.003853,0.009707,0.007231
1382859,3589440,a5d08297343d1c9a6cc82eff919d41ffa5179e95fbb38d...,2017-08-12,0.885838,0.003589,0.008111,1.005659,0.006098,0.144282,0.009497,...,NaN,NaN,NaN,0.006675,0.009127,0.000342,NaN,0.001308,0.009470,0.007563
1382860,1929743,590d8d936b5e7ff008f53b3a34a23e0b26c46c5604f5fa...,2017-10-22,0.773597,0.594307,0.208508,0.073353,0.008069,0.151430,0.001763,...,NaN,NaN,NaN,0.001862,0.003412,0.008345,NaN,0.004714,0.000869,0.008088
1382861,5242852,f27d91300d856f1addb44416f1940277bf3fb2e4fa381e...,2017-08-25,0.653249,0.006837,0.004120,0.812019,0.003227,NaN,0.007285,...,NaN,NaN,NaN,1.000062,0.001197,0.910908,0.219154,1.004851,0.227102,0.091347